### ISSUE TITLE
おさと環境構築

### ISSUE THREAD

**Issue by calm1205** [calm1205/golf_academy#2]
## 概要

環境構築

## 完了条件
- Readmeの環境構築が完了していること
- npm run startができればOK

## 備考

**Comment by satohiro213** [comment]
・　確認用/npm run startの入力結果

satouhironori@satouhironorinoMacBook-Air ~ % npm run start

> my-app@1.0.0 start
> node index.js

**Comment by satohiro213** [comment]
close#2

## 概要

環境構築

## やったこと
- Readmeにある通りの環境構築
-npm run start入力時の出力

satouhironori@satouhironorinoMacBook-Air ~ % npm run start

> my-app@1.0.0 start
> node index.js



## 備考

**Comment by satohiro213** [comment]
@calm1205 
確認お願いします。
