### ISSUE TITLE
吹き出しコンテンツのレイアウト整備

### ISSUE THREAD

**Issue by calm1205** [calm1205/golf_academy#32]
## 概要
<img width="261" alt="スクリーンショット 2023-04-17 8 04 23" src="https://user-images.githubusercontent.com/62320673/232348067-43309c71-1ef4-425e-b51f-2bab05af1a75.png">

## 完了
- 吹き出しコンテンツのレイアウト（高さや余白）が整備できていること

## 備考

**Comment by satohiro213** [comment]
このIssueは＃20吹き出しの補足といったイメージであっていますか？？feature/baloonにpushしました、letter-spacingやlineHeightを調整しましたがこれで完了条件を満たしていますか？？

**Comment by satohiro213** [comment]
@calm1205 コメントしました。
