### ISSUE TITLE
footer&copyright

### ISSUE THREAD

**Issue by calm1205** [calm1205/golf_academy#6]
## 概要
footer下のcopyrightの作成

![Image](https://user-images.githubusercontent.com/62320673/230367868-96c53c6a-6ff0-4224-872a-85d24a88b505.png)

![スクリーンショット_2023-04-06_20_55_21](https://user-images.githubusercontent.com/62320673/230372154-c687fcb1-4542-435f-955c-37433148a089.png)

## 完了条件
- `src/components/footer/copyright.php`で実装されていること
- Figmaのスタイルを参考に同じ見た目を表現できていること

## 備考
- https://www.figma.com/file/0BYv1VK5o7IA5WMJxJHJJL/%E3%82%B4%E3%83%AB%E3%83%95%E3%83%AC%E3%83%83%E3%82%B9%E3%83%B3%E3%82%B5%E3%82%A4%E3%83%88?node-id=109-525&t=OYx6mcM9uX1AnWxO-0

**Comment by satohiro213** [comment]
@calm1205 
プロジェクトボードの確認ができませんでした。リンク切れになってしまいProjectsからも見つかりません。
